fn main() {
    // Demonstrates the expected SMILES output from the Generator + molecule_to_smiles pipeline.
    // Run the real generator with: cargo run  (server) or cargo test (integration tests)
    //
    // For C4H10 (butane) the generator should produce two isomers:
    //   - n-butane:          CCCC
    //   - isobutane:         CC(C)C
    //
    // For C2H2 (acetylene) the generator should produce one isomer:
    //   - acetylene:         C#C
    //
    // For C2H4 (ethylene) the generator should produce one isomer:
    //   - ethylene:          C=C
    //
    // Bond encoding in the adjacency matrix:
    //   0 = no bond
    //   1 = single bond  (no prefix in SMILES)
    //   2 = double bond  (= prefix in SMILES)
    //   3 = triple bond  (# prefix in SMILES)

    println!("Expected SMILES examples (generated by molecule_to_smiles):");
    println!("  C4H10 -> CCCC, CC(C)C");
    println!("  C2H2  -> C#C");
    println!("  C2H4  -> C=C");
    println!("  C3H8  -> CCC");
    println!("  C3H6  -> CC=C  or  C(CC)  (ring via adjacency)");
}

